name: pytest-coverage-comment

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "164-add-coverage-check"]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      # Runs a set of commands using the runners shell          
      - name: Update pip and install testing pkgs
        run: |
          python -VV
          python -m pip install --upgrade pip
          #pip install pytest
          
      - name: Install package and dependencies
        run: |
          python -m pip install --no-deps .
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          #pip freeze >> ~\tests\expected\git_env.txt

      - name: Run tests with coverage
        env:
          usda_API: ${{ secrets.USDA_KEY1 }}
          GEOCODE_API_KEY: ${{ secrets.GEOCODE_API_KEY }}
          REGRID_API_KEY: ${{ secrets.REGRID_API_KEY }}
        run: |
          #pytest -v -s CHAPPIE
          pytest --junitxml=pytest.xml \
          --cov-report=term-missing:skip-covered \
          --cov=CHAPPIE | tee pytest-coverage.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          # Upload test_results
          path: |
            pytest-coverage.txt
            pytest.xml
            

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
